name: Sync with upstream

on:
  schedule:
    - cron: '0 */6 * * *'    # every 6 hours UTC
  workflow_dispatch:         # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Huzaifa4412/synexa-code.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"

      - name: Push changes back to fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/iamzainmunir/synexa-code.git main
